### PR TITLE
feat: Add match metadata to matched postings

### PR DESCRIPTION
**Pull request by JohnMcCann**
I'm unsure of the status of this decade old issue
(https://groups.google.com/g/beancount/c/MU6KozsmqGQ/m/TspjVxx-ZYIJ). This commit adds a config that adds metadata to matched postings such that they can be "linked" to one another.

Alternatives would be using beancount's native links; however, I know in my use case at least I will have transactions with multiple matches (e.g., pay stubs with balances going to: multiple bank accounts, HSA, 401k, etc.). Thus, placing the match metadata at the transaction level is less clear. There is probably some performance hit when querying for matches on a posting level; but I feel that is negligible compared to the improvement in clarity.

The use of random IDs might not be preferred, but I didn't want to try and format some human readable string. All I really care about is being able to pair transactions, not describe the match.

### CODE REVIEW

**Comment by redstreet** [comment]
Thank you for this PR! It's been on the TODO list for a long time :).

One comment: it doesn't seem to be conditionalizing on `match_metadata` if I'm reading this right. Would you mind taking a look? Thanks.

**Comment by JohnMcCann** [comment]
Ha oops, I was reviewing my own code and noticed that... Sorry for being sloppy.

**Comment by redstreet** [comment]
No worries!

It's failing lint, would you mind fixing? Looks good otherwise. Thanks for the unit tests and for explaining design tradeoffs and your choices.

```
flake8 . --count --max-complexity=12 --max-line-length=127 --show-source --statistics
```


```
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib
./beancount_reds_plugins/effective_date/effective_date.py:24:14: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
    return posting.meta is not None and \
             'effective_date' in posting.meta and \
             type(posting.meta['effective_date']) == datetime.date
             ^
./beancount_reds_plugins/effective_date/effective_date.py:210:24: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
                       type(entry.meta['effective_date']) == datetime.date)
                       ^
./beancount_reds_plugins/zerosum/zerosum.py:179:1[5](https://github.com/redstreet/beancount_reds_plugins/actions/runs/7965481689/job/21749420296?pr=25#step:5:5): E2[6](https://github.com/redstreet/beancount_reds_plugins/actions/runs/7965481689/job/21749420296?pr=25#step:5:6)1 at least two spaces before inline comment
random.seed(6) # arbitrary fixed seed
              ^
1     E261 at least two spaces before inline comment
2     E[7](https://github.com/redstreet/beancount_reds_plugins/actions/runs/7965481689/job/21749420296?pr=25#step:5:7)[21](https://github.com/redstreet/beancount_reds_plugins/actions/runs/7965481689/job/21749420296?pr=25#step:5:22) do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
3
Error: Process completed with exit code 1.
```

**Comment by redstreet** [comment]
Merged in #26. Thanks again for this PR, @JohnMcCann!

**Pull request closed without merging**
